Реализация отложенных сигналов (defer)
kruzhok-team/lapki-compiler pull request #25
Opened 2024-05-02 07:54 UTC by L140-beep

Defer в loop.
```cpp
void loop() {
  if (stateChanged) {
      signalDefer = true;
      for (int defer_j = 0; defer_j != defer_i; defer_j++) {
          SIGNAL_DISPATCH(the_sketch, defer[defer_j]);
      }
      signalDefer = false;
      stateChanged = false;
      defer_i = 0;
  }
}
```
Defer в состоянии.
```cpp
        case timer2_timeout_SIG: {
            /*.${SMs::Sketch::SM::global::Выключен::timer2_timeout::[true]} */
            if (true) {
              if (!deferSignal) { // Этот флаг нужен, чтобы при переходе не добавлять старые сигналы, актуально для вложенного defer
                defer[defer_i] = timer2_timeout_SIG;
                defer_i++;
              }
                status_ = Q_HANDLED();
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
```
Объявление defer в sketch.h
```cpp
QSignal defer[1024]; // Сделать настраиваемым?
int defer_i = 0;
bool stateChanged = false;
bool signalDefer = false;
```

P.S.: Защиты от переполнения нет, чуть позже сделаю кольцевой буфер вместо массива

2024-05-18 12:36 UTC, chekoopa requested changes

2024-05-18 12:36 UTC, chekoopa commented on compiler/fullgraphmlparser/templates/preamble_h.txt
> +QSignal defer[1024];
А не слишком большой размер буфера? Память не резиновая. 64 или 128 должно хватить. Накрайняк из метапараметров брать размер (позже приделать).

2024-05-18 12:36 UTC, chekoopa commented on examples/with-defer.xml
> +std::cout &lt;&lt; 'hereee';
Старый формат и плюсовый вывод. Что?

2024-05-19 05:05 UTC, L140-beep commented on examples/with-defer.xml
> +std::cout &lt;&lt; 'hereee';
Старый формат потому что на момент создания PR'a новый формат находился на ревью на стороне библиотеки

2024-05-28 12:35 UTC, chekoopa commented on compiler/fullgraphmlparser/templates/defer_loop.txt
> +      for (int defer_j = 0; defer_j != defer_i; defer_j++) {
Вообще, здесь ещё напрашивается дедупликация сигналов. Ну и нужно понять логику, потому что мы можем оказаться в ситуации, когда после обработки отложенного сигнала мы покидаем текущее состояние, а другие сигналы в своей цепочке могут привести к неопределённому поведению.

Здесь надо следить за этим комментарием.
https://docs.google.com/document/d/14ptmhxw8529gtEFLlNu3IpZ3DhIo0DImQ5RjdHzxm8A/edit?disco=AAABO17Gg9U

2024-05-31 04:02 UTC, L140-beep commented on compiler/fullgraphmlparser/templates/defer_loop.txt
> +      for (int defer_j = 0; defer_j != defer_i; defer_j++) {
Вынес в отдельное issue https://github.com/kruzhok-team/lapki-compiler/issues/35.

2024-05-31 04:03 UTC, merged