Конечные состояния
kruzhok-team/lapki-compiler pull request #34
Opened 2024-05-31 03:30 UTC by L140-beep

2024-06-10 07:50 UTC, chekoopa requested changes
Почини конфликт!

2024-06-10 08:54 UTC, chekoopa requested changes

2024-06-10 08:54 UTC, chekoopa commented on test/test_cgml.py
> +        'examples/choices.graphzml'
Опечатка.

2024-06-10 08:54 UTC, chekoopa commented on examples/choices.graphml
> +>>>>>>> 8dfd478 (pseudostates)
Протёк мерж-конфликт.

2024-06-10 08:54 UTC, chekoopa commented on compiler/handler.py
> +    build_path = base_dir + '/build/'
`os.path.join` же, разве нет? Про слеш на конце тоже надо бы понять.

2024-06-10 08:54 UTC, chekoopa commented on compiler/handler.py
> +            base_dir = BUILD_DIRECTORY + base_dir.replace(' ', '_') + 'sketch/'
`os.path.join` здесь тоже напрашивается.

2024-06-10 08:54 UTC, chekoopa commented on compiler/handler.py
> +            await RequestError(', '.join(e.args)).dropConnection(ws)
Здесь точно не надо их в `str` кастовать? Типа, `map(str, e.args)`.

2024-06-10 08:54 UTC, chekoopa commented on compiler/fullgraphmlparser/graphml_to_cpp.py
> +FINAL_ACTION = 'while(true){}'
Здесь должен быть выход в состояние без событий. Возможно, оно должно при этом продолжать ловить события снаружи. Нужно обратиться к стандарту ПРИМС.

2024-06-10 14:00 UTC, L140-beep commented on compiler/handler.py
> +            await RequestError(', '.join(e.args)).dropConnection(ws)
Я думаю, их надо кастовать, когда args содержит не только строки. Сейчас в CGMLException передаются только строки, но можно кастнуть, чтобы потом об этом не думать

2024-06-10 14:24 UTC, L140-beep commented on compiler/fullgraphmlparser/graphml_to_cpp.py
> +FINAL_ACTION = 'while(true){}'
Посмотрел стандарт, там сказано лишь про остановку работы области

2024-06-11 02:59 UTC, chekoopa approved these changes

2024-06-11 03:00 UTC, merged